### ISSUE TITLE
Undefined Hash Methods in Helper Methods

### ISSUE THREAD

**Issue by itsalljustaride** [lmullen/omeka_client#4]
I'm getting "undefined method" error for the "element_set" Hash in all of the helper methods I try using:

> /Users/johnathb/.rvm/gems/ruby-2.3.1/gems/omeka_client-1.0.0.a/lib/omeka_client/dublin-core.rb:18:in `block in initialize': undefined method `element_set' for #<Hash:0x007f88438f20f0> (NoMethodError)
> 	from /Users/johnathb/.rvm/gems/ruby-2.3.1/gems/omeka_client-1.0.0.a/lib/omeka_client/dublin-core.rb:17:in `each'
> 	from /Users/johnathb/.rvm/gems/ruby-2.3.1/gems/omeka_client-1.0.0.a/lib/omeka_client/dublin-core.rb:17:in `each_with_index'
> 	from /Users/johnathb/.rvm/gems/ruby-2.3.1/gems/omeka_client-1.0.0.a/lib/omeka_client/dublin-core.rb:17:in `initialize'
> 	from /Users/johnathb/.rvm/gems/ruby-2.3.1/gems/omeka_client-1.0.0.a/lib/omeka_client/omeka-collection.rb:22:in `new'
> 	from /Users/johnathb/.rvm/gems/ruby-2.3.1/gems/omeka_client-1.0.0.a/lib/omeka_client/omeka-collection.rb:22:in `initialize'
> 	from /Users/johnathb/.rvm/gems/ruby-2.3.1/gems/omeka_client-1.0.0.a/lib/omeka_client/client.rb:124:in `new'
> 	from /Users/johnathb/.rvm/gems/ruby-2.3.1/gems/omeka_client-1.0.0.a/lib/omeka_client/client.rb:124:in `block in get_all_collections'
> 	from /Users/johnathb/.rvm/gems/ruby-2.3.1/gems/omeka_client-1.0.0.a/lib/omeka_client/client.rb:123:in `each'
> 	from /Users/johnathb/.rvm/gems/ruby-2.3.1/gems/omeka_client-1.0.0.a/lib/omeka_client/client.rb:123:in `get_all_collections'

Using Ruby 2.3.1 and omeka_client 1.0.0.a

Also had to specifically install net-http-persistent --VERSION=2.9 as it did not like 3.0

**Comment by lmullen** [comment]
This software is no longer supported. I've update the README with that information. If you really need it, feel free to fork it and create an updated version.
